name: .NET Framework

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup MSBuild.exe
        uses: warrenbuckley/Setup-MSBuild@v1
      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.0.2
      - name: Restore Nuge Packages
        run: nuget restore RenameTool/RenameTool.sln
      - name: Build library
        run: dotnet build RenameTool/RenameTool/RenameTool.csproj --configuration release
      - name: Build and run .net tests
        run: |
          dotnet build RenameTool/RenameToolIntegrationTest/RenameToolIntegrationTest.csproj
          dotnet test RenameTool/RenameToolIntegrationTeste/RenameToolIntegrationTest.csproj

        
      

      
