name: .NET Framework

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: .NetFramework Action Template
      uses: auycro/netframework-action-template@v0.0.2
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      

      
